# Generated by Django 4.1.7 on 2024-05-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendordetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='contact_details',
            field=models.CharField(max_length=20),
        ),
    ]
